### ISSUE TITLE
Unable to clone repo on Windows

### ISSUE THREAD

**Issue by TaylorN15** [nixiesearch/nixiesearch#332]
Has there been any testing of this on Windows at all? I can't even clone this repository on Windows due to some files containing a colon

```
error: invalid path 'src/test/resources/gpu_test/gpus/0000:41:00.0/information'
error: invalid path 'src/test/resources/gpu_test/gpus/0000:c1:00.0/information'
```

**Comment by shuttie** [comment]
Being honest, we don't plan to support Windows as a first-level target apart from public docker builds: there's llamacpp and onnx native libraries inside, and it's a mess to support an extra windows build for these.

But yes I agree, the git clone issue seems to be weird, will take a look on this.

**Comment by shuttie** [comment]
Seems to be fixed, @TaylorN15 feel free to reopen if you find any issues with the build. But here be dragons.
