### ISSUE TITLE
ONNX inference JVM crash on JDK20

### ISSUE THREAD

**Issue by shuttie** [nixiesearch/nixiesearch#43]
Probably JDK 20 is not the best JDK to run ONNX. 

![image](https://github.com/nixiesearch/nixiesearch/assets/999061/c3b0b3f5-f4f7-4a46-93c7-106c18afbe35)

**Comment by otrosien** [comment]
What about JDK21?

**Comment by shuttie** [comment]
fixed in https://github.com/nixiesearch/nixiesearch/pull/111
